# Generated by Django 4.2.6 on 2023-10-05 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mark_claim_mark'),
        ('users', '0003_remove_customuser_name_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimOfUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.claim')),
            ],
        ),
    ]
