# Generated by Django 3.2.22 on 2023-10-06 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_patronymic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaimOfUser',
        ),
    ]
