# Generated by Django 4.2.5 on 2023-10-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_remove_claim_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
