# Generated by Django 4.2.5 on 2023-10-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
