# Generated by Django 4.2.6 on 2023-10-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mark_claim_mark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mark',
            new_name='Status',
        ),
    ]
