# Generated by Django 4.2.6 on 2023-10-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_mark_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='mark',
            new_name='status',
        ),
    ]
