# Generated by Django 4.2.6 on 2023-10-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_status_options_rename_mark_claim_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
