# Generated by Django 4.2.6 on 2023-10-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_claim_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.ManyToManyField(auto_created='Новая', to='core.status'),
        ),
    ]
